### Numpy is multidimensional array library

In [1]:
import numpy as np
import sys

## The Basics

In [2]:
a = np.array([1,2,3], dtype='int16')
b = np.array([
            [1.0,2.0,3.0], 
            [4.0,5.0,6.0]
             ])

In [3]:
print(a)
print(a.dtype)
print(type(a))

[1 2 3]
int16
<class 'numpy.ndarray'>


In [4]:
print(b)
print(b.dtype)
print(type(b))

[[1. 2. 3.]
 [4. 5. 6.]]
float64
<class 'numpy.ndarray'>


In [5]:
#Get Dimension
print("Dimension", a.ndim)

Dimension 1


In [6]:
# Get Type/Size
print("Type:", b.dtype, ",   Size:", b.itemsize, "bytes")

Type: float64 ,   Size: 8 bytes


In [7]:
#Get total Size
print(a.size * a.itemsize)
print('other way to find this')
print(a.nbytes)

6
other way to find this
6


In [8]:
a.itemsize

2

### Accessing/Changing specific elements, rows, columns, etc

In [9]:
a = np.array([
    [1,2,3,4,5,6,7],
    [11,22,33,44,55,66,77]
])

In [10]:
a.shape

(2, 7)

In [11]:
#accessing elements 
print(a[0])
print(a[1])
print(a[1,5])
print(a[1,:2])
print(a[:,6])

[1 2 3 4 5 6 7]
[11 22 33 44 55 66 77]
66
[11 22]
[ 7 77]


In [12]:
#[startIndex:endIndex:stepSize]
print(a[0, 2::2])
print(a[1, 1:6:3])
print(a[1, 6:0:-2])
print(a[1, -1:-6:-2])

[3 5 7]
[22 55]
[77 55 33]
[77 55 33]


In [13]:
a[1,5] = 20

In [14]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [11, 22, 33, 44, 55, 20, 77]])

In [15]:
a[:,2] = 99

In [16]:
a

array([[ 1,  2, 99,  4,  5,  6,  7],
       [11, 22, 99, 44, 55, 20, 77]])

In [17]:
a[1,3:5] = [40,50]

In [18]:
a

array([[ 1,  2, 99,  4,  5,  6,  7],
       [11, 22, 99, 40, 50, 20, 77]])

#### 3D Array Example

In [19]:
c = np.array([[
            [1,2],
            [3,4]
        ],
        [
            [6,7],
            [8,9]
        ]
])

In [20]:
print(c)
print(c.dtype)

[[[1 2]
  [3 4]]

 [[6 7]
  [8 9]]]
int32


In [21]:
print(c[0,1,1])
print(c[0,1,:])
print(c[0,:,:])
print(c[:,1,1])

4
[3 4]
[[1 2]
 [3 4]]
[4 9]


#### Initializing different types of arrays

In [22]:
# All 0s matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [23]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
# can output ND zero arrays
np.zeros((3,2,3,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [25]:
# All 1s matrix
np.ones((5,2),dtype='int32')

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [26]:
# Any other number
# Syntax: np.full(shape,number)
print(np.full((2,2), (99)))
print("=================")
print(np.full((2,2), (99,1),dtype='float32'))

[[99 99]
 [99 99]]
[[99.  1.]
 [99.  1.]]


<b>Random Decimal Numbers</b> 

In [27]:
print(np.random.rand(3))
print("=================")
print(np.random.rand(5,3))

[0.64953751 0.62522377 0.84762529]
[[0.09653099 0.25576882 0.71964792]
 [0.73230403 0.59000283 0.71789757]
 [0.85078076 0.25121944 0.6363133 ]
 [0.90569446 0.64550919 0.40465931]
 [0.73215342 0.73285244 0.72033462]]


<b>Random Integer Numbers</b> 

In [28]:
print(np.random.randint(3))
print("=================")
# Syntax - start,end,size
print(np.random.randint(2,5,size=(2,3)))

0
[[3 2 3]
 [3 2 2]]


In [29]:
# repeat Array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
r2 = np.repeat(arr,3, axis=1)
print(r1)
print("====")
print(r2)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
====
[[1 1 1 2 2 2 3 3 3]]


#### Challenge
<b>Make the below table</b><br>
1 1 1 1 1<br>
1 0 0 0 1<br>
1 0 9 0 1<br>
1 0 0 0 1<br>
1 1 1 1 1<br>

In [30]:
ch1 = np.ones((5,5))
ch1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [31]:
ch0 = np.zeros((3,3))
ch0[1,1] = 9
ch0

array([[0., 0., 0.],
       [0., 9., 0.],
       [0., 0., 0.]])

In [32]:
ch1[1:4,1:4] = ch0

In [33]:
#Output
ch1

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### Be careful when copying arrays!!!

In [34]:
a = np.array([1,2,3])
b = a
b[0] = 100
print("b: ",b)
print("a: ",a)

b:  [100   2   3]
a:  [100   2   3]


In [35]:
# you see even tho you changed value of b, 
#value of a got changed
# Here b just points to the same place as a
# To prevent it, we need to use .copy() function
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print("b: ",b)
print("a: ",a)

b:  [100   2   3]
a:  [1 2 3]


#### Mathematics

In [36]:
a = np.array([1,2,4,7])
a

array([1, 2, 4, 7])

In [37]:
a + 4

array([ 5,  6,  8, 11])

In [38]:
a - 9

array([-8, -7, -5, -2])

In [39]:
a *= 2
a

array([ 2,  4,  8, 14])

In [40]:
a / 3

array([0.66666667, 1.33333333, 2.66666667, 4.66666667])

In [41]:
b = np.array([2,5,1,9])

In [42]:
a + b

array([ 4,  9,  9, 23])

In [43]:
a ** 2

array([  4,  16,  64, 196])

In [44]:
#take sin
np.sin(a)

array([ 0.90929743, -0.7568025 ,  0.98935825,  0.99060736])

#### Linear Algebra

In [45]:
'''
Multiplication of matrices
condition : matrix-1 shape = (r1,c1)
            matrix-2 shape = (r2,c2)
            For these matrix to multiply, c1 == r2
'''
a = np.ones((3,3))
print("a: ",a)
print()
b = np.full((3,2),(2,4))
print("b: ",b)
print()
print("Matrix Multiplication:\n",np.matmul(a,b))

a:  [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

b:  [[2 4]
 [2 4]
 [2 4]]

Matrix Multiplication:
 [[ 6. 12.]
 [ 6. 12.]
 [ 6. 12.]]


In [46]:
# You can use numpy to find eigen values, determinant, 
# inverse of matrix, identity matrix

#### Statistics

In [47]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
np.min(stats)

1

In [49]:
np.min(stats,axis=1)

array([1, 4])

In [50]:
np.max(stats)

6

In [51]:
np.sum(stats)

21

#### Reorganizing Arrays

In [52]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before) 

[[1 2 3 4]
 [5 6 7 8]]


In [53]:
'''
np.reshape is a function provided by the NumPy library in 
Python, and it is used to change the shape of an array 
without changing its data.
'''
#The no of values has to be same while reshaping
after = before.reshape((4,2))
print(after)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [54]:
before.reshape((8,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [55]:
before.reshape((2,2,2))

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [56]:
# Vertically stacking vectors
'''
numpy.vstack() function is used to stack the 
sequence of input arrays vertically to make a single array.
'''
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [57]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.hstack([v1,v2,v1,v2])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8])

In [58]:
# you can index with a list in NumPy
a = np.array([4,8,3,6,2,1])
a[[1,3,5]]

array([8, 6, 1])

In [59]:
#Accessing matrix
mat = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15],
    [16,17,18,19,20],
    [21,22,23,24,25],
    [26,27,28,29,30]
])

In [60]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [61]:
mat[2:4,0:2]

array([[11, 12],
       [16, 17]])

In [62]:
mat[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [63]:
mat[[0,4,5],3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])